name: My tests workflow

on:
  push:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - run: echos "First workflow was a success"
  prod:
    runs-on: ubuntu-latest
    #needs: [test]
    steps:
       - run: echo "Second workflow was a success"
